# Generated by Django 2.2 on 2022-05-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=32)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('rubro', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProd', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.Proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deuda', models.IntegerField()),
                ('cant_pagado', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('deudor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('deudor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Almacen.Deuda')),
            ],
        ),
    ]
